version: 2
jobs:
  build:
    docker:
      - image: citus/extbuilder:latest

    steps:
      - checkout

      - run:
          name: Greeting
          command: echo Hello, world 2

      - run:
          name: Print the Current Time
          command: date